# docker-compose.yaml
version: "3"
services:
  app:
    build: .
    tty: true
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 80:8080
      - 443:8443
      - 3000:3000
    volumes:
      - ./:/var/www/html/nodejs.com 


